OC_LOC: "{{ lookup('env','OC_LOC') }}"
SED_LOC: "{{ lookup('env','SED_LOC') }}"
AWK_LOC: "{{ lookup('env','AWK_LOC') }}"
GIT_SOURCE_PROJECT: appdev-in-cloud
OCP_USER: openshift-dev
OCP_PASS: devel

# BRMS
BRMS_APP_NAME: brms
BRMS_GIT_REPO_CONTEXT: /discountRules
BRMS_GIT_REPO_BRANCH: master

CARS_APP_NAME: cars
CARS_GIT_REPO: https://github.com/redhatdemocentral/destinasia-services-repo
CARS_GIT_REPO_CONTEXT: /CarWS
CARS_GIT_REPO_BRANCH: master

HOTELS_APP_NAME: hotels
HOTELS_GIT_REPO:  https://github.com/redhatdemocentral/destinasia-services-repo
HOTELS_GIT_REPO_CONTEXT: /HotelWS

FLIGHTS_APP_NAME: flights
FLIGHTS_GIT_REPO:  https://github.com/redhatdemocentral/destinasia-services-repo
FLIGHTS_GIT_REPO_CONTEXT: /FlightWS
FLIGHTS_GIT_REPO_BRANCH: master

FUSE_APP_NAME: fusetravelagency
FUSE_GIT_REPO:  https://github.com/redhatdemocentral/destinasia-services-repo
FUSE_GIT_REPO_CONTEXT: /FuseTravelAgency

